# Generated by Django 4.1.1 on 2022-10-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title_string', models.TextField()),
                ('mrp', models.TextField()),
                ('discountedPrice', models.TextField()),
                ('rating', models.TextField()),
                ('review_count', models.TextField()),
                ('available', models.TextField()),
                ('ram', models.TextField()),
                ('os', models.TextField()),
                ('modelName', models.TextField()),
                ('importer', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
